### ISSUE TITLE
Chat channel chat commands are not supported

### ISSUE THREAD

**Issue by jrdmellow** [jrdmellow/ESOPie#1]
Chat channel chat commands are currently not supported.

ESOPie naively executes chat commands like so;
```SLASH_COMMANDS[command](args)```

This does not work for channel commands such as `/say` `/tell` `/emote` etc. since these commands do not exist in the `SLASH_COMMANDS` table.

**Comment by calamath** [comment]
The original author has an answer for the part of the same process in the other project you referenced. That short code is the conclusion of various discussions by the original author's team, so you are encouraged to adopt it as is.

**Comment by jrdmellow** [comment]
These chat commands are purposely disabled by ZOS (at least partially) and thus will not be supported. There may be some commands that are not explicitly disallowed by ZOS and should be bugged separately.
